=== ntonnaett/wonder/configs/EN325/dtd/cwonder_config.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!--/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
     *                                                                                   *
     *  WONDER - Wave field synthesis Of New Dimensions of Electronic music in Realtime  *
     *  http://swonder.sourceforge.net                                                   *
     *                                                                                   *
     *                                                                                   *
     *  Technische UniversitÃ¤t Berlin, Germany                                           *
     *  Audio Communication Group                                                        *
     *  www.ak.tu-berlin.de                                                              *
     *  Copyright 2006-2008                                                              *
     *                                                                                   *
     *                                                                                   *
     *  This program is free software; you can redistribute it and/or modify             *
     *  it under the terms of the GNU General Public License as published by             *
     *  the Free Software Foundation; either version 2 of the License, or                *
     *  (at your option) any later version.                                              *
     *                                                                                   *
     *  This program is distributed in the hope that it will be useful,                  *
     *  but WITHOUT ANY WARRANTY; without even the implied warranty of                   *
     *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                    *
     *  GNU General Public License for more details.                                     *
     *                                                                                   *
     *  You should have received a copy of the GNU General Public License                *
     *  along with this program; if not, write to the Free Software                      *
     *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.       *
     *                                                                                   *
     * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */ -->


<!ELEMENT cwonder_config (settings,renderpolygon) >

<!ELEMENT settings EMPTY>
<!ATTLIST settings
    projectpath	   CDATA  #REQUIRED
    maxNoSources   CDATA  #REQUIRED
>

<!ELEMENT renderpolygon (point*,elevation) >
<!ATTLIST renderpolygon
    roomname    CDATA  #REQUIRED
>

<!ELEMENT point EMPTY>
<!ATTLIST point
    x	CDATA  #REQUIRED
    y	CDATA  #REQUIRED
    z	CDATA  #REQUIRED
>

<!ELEMENT elevation EMPTY>
<!ATTLIST elevation
    y1	CDATA  #REQUIRED
    z1	CDATA  #REQUIRED
    y2	CDATA  #REQUIRED
    z2	CDATA  #REQUIRED
>

=== ntonnaett/wonder/config/examples/HuFo-draft/cwonder_config.xml
<?xml version="1.0"?>

<!--/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
     *                                                                                   *
     *  WONDER - Wave field synthesis Of New Dimensions of Electronic music in Realtime  *
     *  http://swonder.sourceforge.net                                                   *
     *                                                                                   *
     *                                                                                   *
     *  Technische UniversitÃ¤t Berlin, Germany                                           *
     *  Audio Communication Group                                                        *
     *  www.ak.tu-berlin.de                                                              *
     *  Copyright 2006-2008                                                              *
     *                                                                                   *
     *                                                                                   *
     *  This program is free software; you can redistribute it and/or modify             *
     *  it under the terms of the GNU General Public License as published by             *
     *  the Free Software Foundation; either version 2 of the License, or                *
     *  (at your option) any later version.                                              *
     *                                                                                   *
     *  This program is distributed in the hope that it will be useful,                  *
     *  but WITHOUT ANY WARRANTY; without even the implied warranty of                   *
     *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                    *
     *  GNU General Public License for more details.                                     *
     *                                                                                   *
     *  You should have received a copy of the GNU General Public License                *
     *  along with this program; if not, write to the Free Software                      *
     *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.       *
     *                                                                                   *
     * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */ -->

<!DOCTYPE cwonder_config SYSTEM "cwonder_config.dtd">

<cwonder_config>
<settings projectpath="/home/wfs/wonder3/projects" maxNoSources="64" />
    <renderpolygon roomname="HUFO_WFS">
		<point x="-6.051" y="2.112" z="2.014"/>
		<point x="-5.392" y="2.593" z="2.014"/>
		<point x="-4.695" y="3.018" z="2.014"/>
		<point x="-3.964" y="3.382" z="2.014"/>
		<point x="-3.205" y="3.684" z="2.014"/>
		<point x="-2.424" y="3.921" z="2.014"/>
		<point x="-1.625" y="4.091" z="2.014"/>
		<point x="-0.816" y="4.194" z="2.014"/>
		<point x="0.000" y="4.228" z="2.014"/>
		<point x="0.816" y="4.194" z="2.014"/>
		<point x="1.626" y="4.091" z="2.014"/>
		<point x="2.424" y="3.921" z="2.014"/>
		<point x="3.206" y="3.684" z="2.014"/>
		<point x="3.964" y="3.382" z="2.014"/>
		<point x="4.695" y="3.017" z="2.014"/>
		<point x="5.392" y="2.593" z="2.014"/>
		<point x="6.054" y="2.107" z="2.014"/>
		<point x="6.051" y="-2.112" z="2.014"/>
		<point x="5.392" y="-2.593" z="2.014"/>
		<point x="4.695" y="-3.018" z="2.014"/>
		<point x="3.964" y="-3.382" z="2.014"/>
		<point x="3.205" y="-3.684" z="2.014"/>
		<point x="2.424" y="-3.921" z="2.014"/>
		<point x="1.625" y="-4.091" z="2.014"/>
		<point x="0.816" y="-4.194" z="2.014"/>
		<point x="0.000" y="-4.228" z="2.014"/>
		<point x="-0.816" y="-4.194" z="2.014"/>
		<point x="-1.626" y="-4.091" z="2.014"/>
		<point x="-2.424" y="-3.921" z="2.014"/>
		<point x="-3.206" y="-3.684" z="2.014"/>
		<point x="-3.964" y="-3.382" z="2.014"/>
		<point x="-4.695" y="-3.017" z="2.014"/>
		<point x="-5.392" y="-2.593" z="2.014"/>
		<point x="-6.054" y="-2.107" z="2.014"/>
		<elevation y1="2.014" z1="2.014" y2="2.014" z2="2.014"/>
    </renderpolygon>
</cwonder_config>
